version: '3.8'
services:
  rest-api:
    build:
      context: stockChatApp_backend/.
      args:
        - JASYPT_ENCRYPTOR_PWD=$JASYPT_ENCRYPTOR_PWD
    image: stock-chat-app-restful-api
    container_name: rest-api
    env_file:
      - .env
    environment:
      DATABASE_HOST: postgres_database
    ports:
      - "8080:8080"
    networks:
      - my-network
      - app-network
    external_links:
      - postgres_database

  frontend:
    build: stockChatApp_frontend/.
    image: stock-chat-app-frontend
    ports:
      - "4200:80"
    depends_on: 
      - rest-api
    networks:
      - app-network

networks:
  my-network:
    external: true
  app-network:
    driver: bridge

    
